import { NextResponse } from "next/server";
import { NFT_CONTRACT_ADDRESS } from "../../../../constants/constants";

const {
    ENGINE_URL,
    THIRDWEB_API_SECRET_KEY,
    BACKEND_WALLET_ADDRESS,
} = process.env;

export async function POST(req: Request) {
    if (!ENGINE_URL || !THIRDWEB_API_SECRET_KEY || !BACKEND_WALLET_ADDRESS) {
        throw new Error("Missing environment variables");
    }

    const { userImage, address } = await req.json();
    console.log("userImage", userImage);
    console.log("address", address);

    const requestURL = `${ENGINE_URL}/contract/mumbai/${NFT_CONTRACT_ADDRESS}/erc721/mint-to`;
    console.log(requestURL);

    try {
        const res = await fetch(requestURL, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                Authorization: `Bearer ${THIRDWEB_API_SECRET_KEY}`,
                "x-backend-wallet-address": BACKEND_WALLET_ADDRESS,
            },
            body: JSON.stringify({
                receiver: address,
                metadata: {
                    name: "AI NFT",
                    description: "NFT generated by AI",
                    image: userImage,
                },
            }),
        });

        if (res.ok) {
            const jsonResponse = await res.json();
            console.log("Minted NFT", jsonResponse);
            return NextResponse.json({ message: "Minted NFT Successfully!" });
        } else {
            const errorText = await res.text();
            console.log("Failed to mint NFT", errorText);
            throw new Error("Failed to mint NFT");
        }
    } catch (error) {
        console.error("Error in minting NFT:", error);
        throw error;
    }
}
